# Netlify configuration file

# The command that builds your site
[build]
  command = "npm run build"
  publish = "dist"
  
# Environment variables needed for the build
[build.environment]
  VITE_API_BASE_URL = "/api"
  
# Redirects and proxy rules
[[redirects]]
  # Proxy API requests to your Supabase Edge Function
  from = "/api/*"
  to = "https://prcdxmmidbgfglhuoycm.supabase.co/functions/v1/quick-api/:splat"
  status = 200
  force = true
  # Add headers to authenticate with Supabase
  [redirects.headers]
    Content-Type = "application/json"
    Accept = "application/json"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure proper CORS and caching
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
