# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # ImageKit environment variables (these will be overridden by Netlify UI settings)
  IMAGEKIT_PUBLIC_KEY = "public_Q3GcFOuCqO6UaNe5E6hOc8Lz8XY="
  IMAGEKIT_PRIVATE_KEY = "private_2RRGIB5sFCC+wg8kP8wxotOKCA0="
  IMAGEKIT_URL_ENDPOINT = "https://ik.imagekit.io/erafq13a8"

[dev]
  framework = "#custom"
  command = "vite"
  port = 3000
  targetPort = 3001
  publish = "dist"
  autoLaunch = true
  functionsPort = 3002

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure proper CORS and caching
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
