# Netlify configuration file

# The command that builds your site
[build]
  command = "npm run build"
  publish = "dist"

# Redirects and proxy rules
[[redirects]]
  # Proxy API requests to your Supabase Edge Function
  from = "/api/*"
  to = "https://prcdxmmidbgfglhuoycm.supabase.co/functions/v1/quick-api/:splat"
  status = 200
  force = true
  
  # Add required headers for the Edge Function including authentication
  [redirects.headers]
    Content-Type = "application/json"
    Accept = "application/json"
    # Supabase anon key for Edge Function authentication
    apikey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByY2R4bW1pZGJnZmdsaHVveWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTMxMTAsImV4cCI6MjA2NTYyOTExMH0.MxuaZ4eN_H2B3XA-WnLuiAG7ZpOuFewaayXbqbA0Ydc"
    Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByY2R4bW1pZGJnZmdsaHVveWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTMxMTAsImV4cCI6MjA2NTYyOTExMH0.MxuaZ4eN_H2B3XA-WnLuiAG7ZpOuFewaayXbqbA0Ydc"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure proper CORS and caching
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
